name: Temp Export Wibo Source

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: decompals/wibo
          ref: 1.2.0
          path: wibo
      - uses: actions/upload-artifact@v4
        with:
          name: wibo-modules-source
          path: wibo/src/modules.cpp
